### ISSUE TITLE
STEP files

### ISSUE THREAD

**Issue by lousassole** [PyottDesign/Statial-b#1]
Hello,

Is there any chance of getting the STEP and/or F3d files so I can modify this shell?
I'd like to make it fit my G903 boards, add a couple more thumb buttons, and add a thumb/pinky rest. This will all be much easier to do with the step/f3d files over the stl meshes.
I can release the modified parts to your repo, or fork it if you'd prefer. 
I'd rather not re-do all the hard work you've already done with the design and engineering to make the mouse so flexible and good looking. Either way, I appreciate the work you did and hope to see more of it! 
Thank you.

**Comment by PyottDesign** [comment]
Added a zipped STEP file under the /3d_printables directory.
Thanks for taking interest in the project but, as a waring, fitting a different control board into the Statial.b is going to be difficult. The ball joints for holding the adjustable surfaces are packed in very tightly so even a few mm shift will cause a lot of cascading changes to the mechanics.
It's an issue I ran into a lot during the mechanical development where I would make a minor change to one part and then have to update all the adjacent sub-parts to fit. Changing those sub-parts would influence all their surrounding parts, etc.
