### ISSUE TITLE
License terms for electrical/mechanical portion of design?

### ISSUE THREAD

**Issue by bdgackle** [PyottDesign/Statial-b#2]
I see the MIT license in the code.

It would be nice to include one for the overall project -- either some CC variant to specify what's allowed, or perhaps just a clarifying statement that this is intended just for personal use if that is the case.  (Either way, thank you for putting this out there!).

I'm planning to build one of these, but would be making some changes -- would love to fork the repo publically if I come up with anything useful.  That seems to be clearly allowed for the firmware, but it's not clear what is okay for the electrical and mechanical design.

It would also be interesting to know whether people could offer kitted parts for sale based on this.  That's probably not something I'd ever get to personally, but I'd certainly love it if someone did.

**Comment by PyottDesign** [comment]
Added CERN Open Hardware License (Permissive) for 3D prints & Gerber files. This should give the most flexibility for editing & repurposing the design.
