### ISSUE TITLE
Adding explicit scope to project and what amenable requests would look like.

### ISSUE THREAD

**Issue by anadon** [PyottDesign/Statial-b#3]
Hello,

This project looks very interesting and is something I'm interested in.  I've been needing a repairable and durable mouse due to disability.  It seems like this project is almost that.  I have to face up to the fact that I have neither the time nor the skills to meaningfully contribute the related changes.  There might be a whole bunch of people like me who come rushing wanting freebies, and when I looked upstream and here I didn't see anything to state that the project would expand to accommodate, or only accept minor changes or improvements.  I believe adding a small section to the README about scope and amenable changes might save you some future trouble.

Feel free to close this out at your leisure.

**Comment by PyottDesign** [comment]
Thanks for the interest in the project. Unfortunately I’m not at a place where I can do custom design requests for the Statial right now. I do plan on continuing incremental improvements and light-weighting on the design in the future. I also may do an alternate smooth external surface set (the lattice design getting dirty seemed to trigger a lot of people on YouTube) but that’s all I’m planning on at the moment.
I clarified the licensing language for the hardware so there’s nothing preventing anyone from forking or downloading the design and iterating on it as they like. That would be really cool to see so I hope someone does it.
