### ISSUE TITLE
A little bit wrong wire on encoder

### ISSUE THREAD

**Issue by DreaM117er** [PyottDesign/Statial-b#4]
![Acrobat_REJEAuk3wL](https://github.com/user-attachments/assets/f02e8612-35d7-4956-889e-5e42f649348a)

GND is the middle one, I step the PDF file, but the encoder can't drive.

BTW, it is crazy design, great work.

**Comment by PyottDesign** [comment]
Mouse wheel rotary encoders have the common ground on one side, B in the center and A on the other side vs normal encoders with ground center.  I've wired a bunch of these up and just triple checked the wiring on the one I'm using right now, just to make sure I wasn't going crazy. The diagram in the PDF should be working a-ok.
[Kailh mouse rotary encoder details](https://www.kailhswitch.com/info/the-inruduction-of-mouse-wheel-rotary-encoder-33169856.html)
![kail-rotary](https://github.com/user-attachments/assets/b212f6d2-63bf-4384-8e64-a8246d5bee55)

**Comment by DreaM117er** [comment]
Oh really!? It have different problem when I  first test.

woooo, it's so great. Thank you tell me where I got wrong.

but I think the compoment HW-06 is really difficult to collect from anybody. Have you an idea to swap this one?

**Comment by PyottDesign** [comment]
Huh, strange. Please let me know what you find. I want to make the instructions as clear as possible so if there is something in the wiring that was confusing or not working, please point it out.

HW-06 (1/8 inch aluminum tube stock) should be swappable with any 3mm diameter metric aluminum tube.  Something like this  [3mm OD x 0.45mm wall x 300mm](https://ksmetals.com/products/al45mm-3?variant=42832533979383&currency=USD&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic) should be available internationally.

Let me know how it goes and if you have any other questions or comments. Glad you are interested in the project!
